### ISSUE TITLE
NuGet package for 0.2.0 refers to 0.1.1.1 binaries

### ISSUE THREAD

**Issue by Zastai** [phw/dotnet-discid#1]
Creating a dummy console application and adding the current NuGet package leads to:

<root>\packages\DotNetDiscId.0.2.0.0\build\DotNetDiscId.targets(7,5): error MSB3030: Could not copy the file "<root><project>..\packages\DotNetDiscId.0.1.1.1\build\native\win32\discid.dll" because it was not found.

The .targets file indeed refers to these locations (hardcoded, not via some property).

**Comment by phw** [comment]
That's stupid, I'll see if I can make this dynamic.

**Comment by phw** [comment]
This was fixed by PR #3
